### PR TITLE
Fixes https://github.com/NoXF/libwebp-sys/issues/29

### PR DESCRIPTION
**Pull request by lilith**

### CODE REVIEW

**Comment by NoXF** [comment]
it seems not to pass all the tests. can you try to fix them

**Comment by lilith** [comment]
Can you share your test run failures? I don't see any CI executions. This only disables debug info generation, so it would be bizarre for it to change test results.

**Comment by lilith** [comment]
Although, it does set opt-level=2 for the test profile, so it's probably that.. the tests simply haven't been running with optimizations before, and thus haven't been catching release-mode issues. Consider running both cargo test and cargo test --release in CI.

**Comment by NoXF** [comment]
The failed CI information can be found in the commit of your fork branch. It's not a big problem just a format error and a 
wasm target error(maybe introduced by a wasm upgrade). 

> emcc: error: unsupported target: wasm32-unknown-unknown (emcc only supports wasm64-unknown-emscripten and wasm32-unknown-emscripten)

and I have written a CI fix branch, you can refer to whether it works

**Pull request merged**
